name: Node.js CD

on:
  workflow_dispatch:
    inputs:
      reason:
        description:  "Why are you running this mannually?"
        required: true
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: teset manual echo run
      run: |
          echo "reason: ${{ github.event.inputs.reason }}!