name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.9
        ports:
            - 5432:5432
        env:
          POSTGRES_USER: postgresmobilea
          POSTGRES_PASSWORD: postgresmobilea
          POSTGRES_DB: mobilea
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: npm install
      run: npm install
    - name: run lint code
      run: npm run lint
    - name: run db push & test code
      run: npm run db-push:ci && npm run test:ci
      env:
          SCHEMA_NAME: test
          DATABASE_URL: postgresql://postgresmobilea:postgresmobilea@localhost:5432/mobilea?schema=test

  release:
    if: github.repository == 'OPGG-HACKTHON/mobile-a-backend'
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: release
      run: echo release
    - name: check reponame
      run: echo ${{ github.repository }}

  deploy:
    if: github.repository == 'OPGG-HACKTHON/mobile-a-backend'
    needs: [build, release]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: deploy
      run: echo deploy
    - name: check reponame
      run: echo ${{ github.repository }}