name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: npm install
      run: npm install
    - name: run lint code
      run: npm run lint
    - name: run db push & test code
      run: npm run db-push:ci && npm run test:ci

  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: release
      run: echo release

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: deploy
      run: echo deploy